// ============================================================
//  FIFA WORLD CUP 2026 — COMPLETE DATA
//  All UTC timestamps. IST = UTC + 5:30 (330 min).
// ============================================================

const TEAMS = {
  // GROUP A
  mexico:       { name:"Mexico",        flag:"🇲🇽", group:"A", colors:["#006847","#CE1126"], fifa_rank:16, pop:"130M", cap:"Mexico City", founded:1927, wc_apps:17, best:"Quarterfinals (1970, 1986)", bio:"Los Tri have long been the dominant force of CONCACAF, qualifying for every World Cup since 1994. Known for their passionate 'Grito' fans and tenacious defensive style. Hosted two World Cups (1970, 1986) and are co-hosting 2026 — a homecoming they intend to celebrate deep into the tournament.", trivia:"Mexico beat Bulgaria via penalties at 1986 WC in Mexico City — the first penalty shootout in WC history." },
  south_africa: { name:"South Africa",  flag:"🇿🇦", group:"A", colors:["#007A4D","#FFB81C"], fifa_rank:60, pop:"60M",  cap:"Pretoria", founded:1991, wc_apps:3, best:"Group Stage (2010)", bio:"Bafana Bafana are the only African nation to host a World Cup (2010). Their golden generation of Benni McCarthy and Lucas Radebe has faded, but new talent has emerged through the PSL. 2026 marks their return to the world stage after missing the 2014 and 2018 tournaments.", trivia:"South Africa became the first and only host nation to be eliminated in the group stage at 2010 WC." },
  south_korea:  { name:"South Korea",   flag:"🇰🇷", group:"A", colors:["#003478","#CD2E3A"], fifa_rank:23, pop:"52M",  cap:"Seoul", founded:1928, wc_apps:11, best:"4th Place (2002)", bio:"The Taeguk Warriors shocked the world at 2002 by reaching the semi-finals on home soil. Captain Heung-min Son leads a modern crop of players thriving in Europe's top leagues. Kim Min-jae anchors one of Asia's strongest defensive units, making them dark horses in 2026.", trivia:"South Korea's 2002 semi-final run was the best performance by any Asian team in World Cup history." },
  czechia:      { name:"Czechia",       flag:"🇨🇿", group:"A", colors:["#D7141A","#11457E"], fifa_rank:37, pop:"11M",  cap:"Prague", founded:1901, wc_apps:10, best:"Runner-up (1934, 1962) as Czechoslovakia", bio:"As Czechoslovakia, they were World Cup runners-up twice. The modern Czech Republic has competitive squads and regularly qualifies through UEFA playoffs. Tomas Soucek and Patrik Schick lead a physically strong unit that punches above its weight.", trivia:"Czechoslovakia's Antonín Panenka invented the iconic 'Panenka' penalty chip at Euro 1976, inspiring generations." },
  // GROUP B
  canada:       { name:"Canada",        flag:"🇨🇦", group:"B", colors:["#FF0000","#FFFFFF"], fifa_rank:38, pop:"38M",  cap:"Ottawa", founded:1912, wc_apps:3, best:"Group Stage (1986, 2022)", bio:"Canada's 2022 World Cup qualification ended a 36-year absence. Alphonso Davies and Jonathan David lead a golden generation. As co-hosts in 2026, Canada aims to finally progress past the group stage for the first time in their history, backed by fanatical home crowds.", trivia:"Canada's Alphonso Davies became the first Canadian to score at a World Cup when he netted against Croatia in 2022." },
  bosnia:       { name:"Bosnia & Herz.", flag:"🇧🇦", group:"B", colors:["#002395","#FFCD00"], fifa_rank:66, pop:"3.3M", cap:"Sarajevo", founded:1992, wc_apps:2, best:"Group Stage (2014)", bio:"Bosnia's debut at 2014 showed their quality with Edin Džeko and Miralem Pjanic at the helm. The new generation must forge their own identity, but technical skill runs through Bosnian football DNA. Their passing game under pressure can unlock any defence.", trivia:"Bosnia qualified for their first-ever World Cup in 2014 — just 22 years after the country was formed." },
  qatar:        { name:"Qatar",         flag:"🇶🇦", group:"B", colors:["#8D1B3D","#FFFFFF"], fifa_rank:72, pop:"2.9M", cap:"Doha", founded:1960, wc_apps:2, best:"Group Stage (2022)", bio:"Qatar became the first host nation to be eliminated in the group stage at 2022. Their qualification for 2026 through Asian competition shows real development. The 'Maroons' rely heavily on naturalised players but have improved coaching structures since hosting the tournament.", trivia:"Qatar's 2022 opening loss to Ecuador was the first time a World Cup host nation lost their opening game." },
  switzerland:  { name:"Switzerland",   flag:"🇨🇭", group:"B", colors:["#FF0000","#FFFFFF"], fifa_rank:13, pop:"8.8M", cap:"Bern", founded:1895, wc_apps:12, best:"Quarterfinals (1934, 1938, 1954)", bio:"Switzerland punch well above their weight. Consistent knockout stage qualifiers since 2014, they have beaten France (Euro 2021) and Spain in recent tournaments. Granit Xhaka's leadership and Yann Sommer's goalkeeping make them dangerous opponents for any team.", trivia:"Switzerland hosted the very first FIFA World Cup draw in 1954 — in their own backyard." },
  // GROUP C
  brazil:       { name:"Brazil",        flag:"🇧🇷", group:"C", colors:["#009C3B","#FFDF00"], fifa_rank:5, pop:"215M",  cap:"Brasília", founded:1914, wc_apps:22, best:"Winners (1958,62,70,94,2002)", bio:"The Seleção are the most decorated team in World Cup history with five titles. Vinicius Jr leads the current side with explosive pace and flair. Brazil haven't won since 2002 and the hunger for a sixth star burns bright. Their squad blends world-class talent with South American grit.", trivia:"Brazil is the only country to have participated in EVERY FIFA World Cup since its inception in 1930." },
  morocco:      { name:"Morocco",       flag:"🇲🇦", group:"C", colors:["#C1272D","#006233"], fifa_rank:14, pop:"37M",  cap:"Rabat", founded:1955, wc_apps:7, best:"Semi-finals (2022)", bio:"Atlas Lions made history at Qatar 2022 by becoming the first African team to reach the semi-finals. Hakimi, Boufal, and En-Nesyri galvanised a nation. Their defensive solidity and passionate counter-attacking style make them genuine dark horses in 2026.", trivia:"Morocco conceded only 3 goals in 6 games at the 2022 World Cup — a record for a debutant semi-finalist." },
  haiti:        { name:"Haiti",         flag:"🇭🇹", group:"C", colors:["#00209F","#D21034"], fifa_rank:83, pop:"12M",  cap:"Port-au-Prince", founded:1904, wc_apps:2, best:"Round of 16 (1974)", bio:"Haiti had a memorable 1974 debut, and their return to 2026 after decades away is celebrated as a triumph of perseverance. The country's football has overcome extraordinary hardship — natural disasters, political instability — to qualify. This squad plays with fearless joy.", trivia:"Haiti's Manno Sanon scored one of 1974's great goals, beating the legendary Dino Zoff to equalise against Italy." },
  scotland:     { name:"Scotland",      flag:"🏴󠁧󠁢󠁳󠁣󠁴󠁿", group:"C", colors:["#003078","#FFFFFF"], fifa_rank:29, pop:"5.5M", cap:"Edinburgh", founded:1873, wc_apps:9, best:"Group Stage (multiple)", bio:"The world's oldest national team finally end a 28-year World Cup absence. Scotland vs England remains football's oldest rivalry. Andy Robertson marshals an experienced squad that qualified through sheer defensive determination. Their Tartan Army fans travel in thousands and create unmatched atmospheres.", trivia:"Scotland played England in the world's first-ever international football match in 1872, drawing 0-0 in Glasgow." },
  // GROUP D
  usa:          { name:"USA",           flag:"🇺🇸", group:"D", colors:["#002868","#BF0A30"], fifa_rank:14, pop:"336M", cap:"Washington D.C.", founded:1913, wc_apps:12, best:"3rd Place (1930), R16 (2002, 2022)", bio:"Co-hosts and rising force. The USMNT's golden generation — Pulisic, McKennie, Weah, Musah, Adams — are all in their primes. Playing on home soil at packed stadiums adds massive momentum. A semi-final run is the minimum ambition for the country co-hosting the world's biggest event.", trivia:"The USA beat England 1-0 in their debut game at the 1950 World Cup — considered one of the greatest upsets ever." },
  paraguay:     { name:"Paraguay",      flag:"🇵🇾", group:"D", colors:["#D52B1E","#009B48"], fifa_rank:39, pop:"7.4M", cap:"Asunción", founded:1906, wc_apps:9, best:"Quarterfinals (2010)", bio:"La Albirroja are masters of tight, disciplined football. Miguel Almirón and Enciso bring flair to a traditionally tenacious side. Paraguay's physical conditioning in South America's altitude qualifiers makes them durable competitors over a long tournament.", trivia:"Paraguay holds the record for the longest World Cup unbeaten run without winning the tournament (11 games, 2010 WC)." },
  australia:    { name:"Australia",     flag:"🇦🇺", group:"D", colors:["#00843D","#FFD700"], fifa_rank:26, pop:"26M",  cap:"Canberra", founded:1961, wc_apps:7, best:"Round of 16 (2006, 2022)", bio:"The Socceroos' 2022 run to the Round of 16 inspired a generation. Martin Boyle, Mat Ryan, and an emerging core carry the torch. Australian football has professionalised rapidly, with many players now starring across Europe's top leagues.", trivia:"Australia's Harry Kewell scored one of the tournament's greatest goals to save the Socceroos at the 2006 World Cup." },
  turkiye:      { name:"Türkiye",       flag:"🇹🇷", group:"D", colors:["#E30A17","#FFFFFF"], fifa_rank:25, pop:"85M",  cap:"Ankara", founded:1923, wc_apps:3, best:"3rd Place (2002)", bio:"Turkey shocked the world at 2002, reaching third place. The current generation — Arda Güler, Calhanoglu, Demiral — is the most talented since then. Young Real Madrid star Arda Güler's dribbling has electrified European football and he could be the breakout star of 2026.", trivia:"Hakan Şükür scored the fastest goal in World Cup history (11 seconds) for Turkey vs South Korea at the 2002 WC." },
  // GROUP E
  germany:      { name:"Germany",       flag:"🇩🇪", group:"E", colors:["#000000","#DD0000"], fifa_rank:12, pop:"84M",  cap:"Berlin", founded:1900, wc_apps:20, best:"Winners (1954,74,90,2014)", bio:"Die Mannschaft have won four World Cups and are perennial contenders. After early exits in 2018 and 2022, Germany rebuilt under Julian Nagelsmann with Florian Wirtz and Jamal Musiala leading a thrilling new generation. They want to prove 2014 wasn't the end — just an intermission.", trivia:"Germany's 7-1 destruction of host Brazil in the 2014 semi-final is widely considered the greatest upset in WC history." },
  curacao:      { name:"Curaçao",       flag:"🇨🇼", group:"E", colors:["#002B7F","#F9E814"], fifa_rank:88, pop:"155K", cap:"Willemstad", founded:1921, wc_apps:1, best:"World Cup Debut (2026)", bio:"Making their World Cup debut, Curaçao is one of 2026's most remarkable stories. The island of 155,000 people qualified through CONCACAF. With players raised in the Netherlands' youth system, they combine European technique with Caribbean passion. Every match is historic for them.", trivia:"Curaçao is the smallest country by population (155,000) ever to qualify for a FIFA World Cup." },
  ivory_coast:  { name:"Ivory Coast",   flag:"🇨🇮", group:"E", colors:["#F77F00","#009A44"], fifa_rank:33, pop:"27M",  cap:"Yamoussoukro", founded:1960, wc_apps:4, best:"Group Stage (2006, 2010, 2014)", bio:"Les Éléphants carry the legacy of Didier Drogba and Yaya Touré. The current generation including Sébastien Haller and Nicolas Pépé brings Premier League quality. AFCON champions in 2024, their confidence heading into 2026 has never been higher.", trivia:"Ivory Coast's 2006 group included Argentina, Netherlands, and Serbia — considered the 'Group of Death'." },
  ecuador:      { name:"Ecuador",       flag:"🇪🇨", group:"E", colors:["#FFD100","#003580"], fifa_rank:44, pop:"18M",  cap:"Quito", founded:1925, wc_apps:4, best:"Round of 16 (2006, 2022)", bio:"La Tri punched above their weight at 2022, opening the tournament with a win. Enner Valencia remains their talisman, while younger players Moisés Caicedo and Jeremy Sarmiento bring Premier League quality. High altitude training in Quito gives them unique physical advantages.", trivia:"Ecuador's Enner Valencia scored all three of his country's goals at the 2014 World Cup, becoming their all-time WC top scorer." },
  // GROUP F
  netherlands:  { name:"Netherlands",   flag:"🇳🇱", group:"F", colors:["#FF4F00","#FFFFFF"], fifa_rank:7, pop:"17.9M", cap:"Amsterdam", founded:1889, wc_apps:11, best:"Runner-up (1974, 1978, 2010)", bio:"Three-time runners-up, the Dutch have never lifted the trophy they deserve. Virgil van Dijk's leadership and Memphis Depay's creativity anchor a squad with genuine title ambitions. The famous 'Clockwork Orange' attacking philosophy lives on in a new generation.", trivia:"Johan Cruyff's Netherlands invented 'Total Football' — the revolutionary 1974 system that changed football forever." },
  japan:        { name:"Japan",         flag:"🇯🇵", group:"F", colors:["#BC002D","#FFFFFF"], fifa_rank:18, pop:"124M", cap:"Tokyo", founded:1921, wc_apps:8, best:"Round of 16 (2002, 2022)", bio:"The Samurai Blue sent shockwaves through 2022, defeating both Germany and Spain. Takehiro Tomiyasu, Daichi Kamada, and Kaoru Mitoma are established Premier League and Bundesliga players. Japan's fearless pressing system neutralises bigger opponents.", trivia:"Japan became the first Asian team to beat Spain at a World Cup, pulling off a stunning comeback at Qatar 2022." },
  sweden:       { name:"Sweden",        flag:"🇸🇪", group:"F", colors:["#006AA7","#FECC02"], fifa_rank:24, pop:"10.5M", cap:"Stockholm", founded:1904, wc_apps:12, best:"3rd Place (1994, 1950)", bio:"Sweden surprised everyone at 2018, reaching the quarter-finals. A solid defensive unit around Alexander Isak and Dejan Kulusevski in attack makes them hard to beat. Post-Ibrahimovic, Sweden has rediscovered its collective identity.", trivia:"Zlatan Ibrahimovic once scored a stunning 35-yard bicycle kick against England in 2012 — still considered the greatest individual goal in Swedish football history." },
  tunisia:      { name:"Tunisia",       flag:"🇹🇳", group:"F", colors:["#E70013","#FFFFFF"], fifa_rank:36, pop:"12.1M", cap:"Tunis", founded:1956, wc_apps:6, best:"Group Stage (multiple)", bio:"Les Aigles de Carthage nearly qualified for the Round of 16 at 2022, defeating France in their final match. Wahbi Khazri leads a technically gifted side. Tunisia's combination of European-based professionals and domestic talent makes them unpredictable opponents.", trivia:"Tunisia became the first African team to win a World Cup match when they beat Mexico 3-1 at the 1978 tournament." },
  // GROUP G
  belgium:      { name:"Belgium",       flag:"🇧🇪", group:"G", colors:["#000000","#F50000"], fifa_rank:3, pop:"11.6M",  cap:"Brussels", founded:1895, wc_apps:14, best:"3rd Place (2018)", bio:"The Red Devils' 'Golden Generation' of De Bruyne, Hazard, and Lukaku produced a 3rd-place finish in 2018. De Bruyne remains world-class while younger talents like Doku and Openda inject pace. Belgium desperately want to win the trophy that has eluded their most talented generation.", trivia:"Belgium finished 3rd at 2018 despite being world No.1 — the highest-ranked team to finish third in WC history." },
  egypt:        { name:"Egypt",         flag:"🇪🇬", group:"G", colors:["#C8102E","#000000"], fifa_rank:35, pop:"105M", cap:"Cairo", founded:1921, wc_apps:4, best:"Group Stage (1934, 1990)", bio:"Mohamed Salah finally gets his World Cup. The Liverpool legend is Egypt's all-time scorer and their inspiration. Egypt qualified after years of heartbreak. Salah-inspired, with a strong defensive structure, The Pharaohs aim to progress beyond the group stage for the first time.", trivia:"Egypt were Africa's first World Cup representatives, appearing at the 1934 tournament in Italy." },
  iran:         { name:"Iran",          flag:"🇮🇷", group:"G", colors:["#239F40","#FFFFFF"], fifa_rank:22, pop:"87M",  cap:"Tehran", founded:1920, wc_apps:7, best:"Group Stage (multiple)", bio:"Team Melli have appeared at the last three World Cups. Sardar Azmoun and Mehdi Taremi lead an attack that can unsettle European sides. Iran qualified comfortably through the AFC and bring a technically sound, compact defensive approach.", trivia:"Iran's match vs USA at the 1998 World Cup was dubbed 'the most politically charged match in World Cup history'." },
  new_zealand:  { name:"New Zealand",   flag:"🇳🇿", group:"G", colors:["#00247D","#CC0000"], fifa_rank:94, pop:"5.1M", cap:"Wellington", founded:1891, wc_apps:3, best:"Group Stage (1982, 2010)", bio:"The All Whites are Pacific football's finest. They drew all three matches at 2010, not losing a single game. Chris Wood leads a hardworking, physically imposing side that can make life difficult for the tournament's heavyweights.", trivia:"New Zealand were the only team at the 2010 World Cup to go undefeated — drawing all 3 games but still going out." },
  // GROUP H
  spain:        { name:"Spain",         flag:"🇪🇸", group:"H", colors:["#AA151B","#F1BF00"], fifa_rank:6, pop:"47.7M", cap:"Madrid", founded:1909, wc_apps:16, best:"Winners (2010)", bio:"La Roja dominated world football from 2008-2012 with their tiki-taka philosophy. Lamine Yamal, Pedri, and Rodri represent a new generation redefining Spanish brilliance. 2026 offers Spain the chance to equal Brazil and Germany with 4 World Cup titles.", trivia:"Spain's 2010 campaign included the final's only goal — Andrés Iniesta's 116th-minute winner against Netherlands." },
  cape_verde:   { name:"Cape Verde",    flag:"🇨🇻", group:"H", colors:["#003893","#CF2027"], fifa_rank:77, pop:"560K", cap:"Praia", founded:1982, wc_apps:1, best:"World Cup Debut (2026)", bio:"Making their sensational World Cup debut, the Blue Sharks are African football's most remarkable 2026 story. Largely built on players with Portuguese backgrounds, Cape Verde play direct, energetic football. Their island nation of 560,000 will pack stadiums with the most passionate fans per capita at the tournament.", trivia:"Cape Verde's population of 560,000 makes this one of the smallest nations ever to qualify for a World Cup." },
  saudi_arabia: { name:"Saudi Arabia",  flag:"🇸🇦", group:"H", colors:["#006C35","#FFFFFF"], fifa_rank:56, pop:"35M",  cap:"Riyadh", founded:1959, wc_apps:7, best:"Round of 16 (1994)", bio:"Al-Akhdar shocked the world by beating Argentina 2-1 at 2022. The Saudi Pro League has become a destination for world-class players, and some of that quality has filtered into the national team. They play with more confidence than ever before.", trivia:"Saudi Arabia's 2022 win over Argentina was statistically the biggest upset in World Cup history by FIFA rankings." },
  uruguay:      { name:"Uruguay",       flag:"🇺🇾", group:"H", colors:["#5AAAFF","#FFFFFF"], fifa_rank:17, pop:"3.6M", cap:"Montevideo", founded:1900, wc_apps:14, best:"Winners (1930, 1950)", bio:"The original World Cup champions (1930, 1950) from South America's smallest country. Darwin Núñez and Federico Valverde lead a warrior generation. Uruguay's 'garra charrúa' spirit — fierce determination — is football legend. They never give up and have the quality to win.", trivia:"Uruguay won the very first World Cup in 1930 on home soil, defeating Argentina 4-2 in the Montevideo final." },
  // GROUP I
  france:       { name:"France",        flag:"🇫🇷", group:"I", colors:["#003189","#FFFFFF"], fifa_rank:2, pop:"68M",   cap:"Paris", founded:1919, wc_apps:16, best:"Winners (1998, 2018)", bio:"Les Bleus are two-time world champions and perennial title favourites. Kylian Mbappé leads arguably the most talented squad in the tournament. With strength across every position, France have the depth to win regardless of injuries. 2026 could be Mbappé's defining moment.", trivia:"France fielded the youngest starting XI in a World Cup final in 2018 and still won 4-2 against Croatia." },
  senegal:      { name:"Senegal",       flag:"🇸🇳", group:"I", colors:["#00853F","#FDEF42"], fifa_rank:20, pop:"17.8M", cap:"Dakar", founded:1960, wc_apps:4, best:"Quarterfinals (2002)", bio:"The Lions of Teranga are Africa's most consistent performers. Sadio Mané's legacy inspired a generation, and AFCON champions 2021/22. Ismaïla Sarr and Nampalys Mendy lead a team built on fitness, teamwork, and tactical intelligence. Senegal can beat anyone on their day.", trivia:"Senegal beat France — the defending champions — 1-0 at their very first World Cup game in 2002." },
  iraq:         { name:"Iraq",          flag:"🇮🇶", group:"I", colors:["#CE1126","#FFFFFF"], fifa_rank:63, pop:"42M",  cap:"Baghdad", founded:1948, wc_apps:2, best:"Group Stage (1986)", bio:"Iraq's return to the World Cup after nearly four decades is a triumph. The Asian Cup champions in 2007, they've rebuilt under consistent coaching. Aymen Hussein leads a technically gifted side who aren't here just to participate — they want to make history.", trivia:"Iraq won the 2007 Asian Cup — the greatest moment in their football history, lifting the trophy in Jakarta." },
  norway:       { name:"Norway",        flag:"🇳🇴", group:"I", colors:["#EF2B2D","#FFFFFF"], fifa_rank:30, pop:"5.5M", cap:"Oslo", founded:1902, wc_apps:3, best:"Round of 16 (1998)", bio:"Norway returns to the World Cup on the strength of Erling Haaland. The Manchester City striker is arguably the world's deadliest finisher. Ødegaard's creativity from Arsenal, plus Haaland's goals, makes Norway a lethal attacking unit. Their defensive structure around these stars will be key.", trivia:"Norway beat Brazil 2-1 at the 1998 World Cup in one of the tournament's biggest shocks, knocking out the eventual runners-up." },
  // GROUP J
  argentina:    { name:"Argentina",     flag:"🇦🇷", group:"J", colors:["#75AADB","#FFFFFF"], fifa_rank:1, pop:"46M",   cap:"Buenos Aires", founded:1893, wc_apps:18, best:"Winners (1978, 1986, 2022)", bio:"Defending champions led by the greatest player of all time, Lionel Messi. At 38, this could be Messi's last dance, adding incredible emotional weight to Argentina's campaign. Enzo Fernández, Julián Álvarez, and Rodrigo De Paul make this one of the tournament's most complete squads.", trivia:"Messi's 2022 World Cup performance — 7 goals, 3 assists, one Ballon d'Or — is considered the greatest individual WC performance since Maradona in 1986." },
  algeria:      { name:"Algeria",       flag:"🇩🇿", group:"J", colors:["#006233","#FFFFFF"], fifa_rank:53, pop:"45M",  cap:"Algiers", founded:1962, wc_apps:5, best:"Round of 16 (2014)", bio:"Les Fennecs impressed at 2014 with an attacking, entertaining style. AFCON 2019 champions, Algeria built around Riyad Mahrez's creativity. The current squad blends experienced European-based professionals with hungry domestic talent eager to create new history.", trivia:"Algeria's 1982 win over West Germany — the reigning European Champions — is one of the biggest upsets in World Cup history." },
  austria:      { name:"Austria",       flag:"🇦🇹", group:"J", colors:["#ED2939","#FFFFFF"], fifa_rank:27, pop:"9.1M", cap:"Vienna", founded:1904, wc_apps:8, best:"3rd Place (1954)", bio:"Austria's 'Wunderteam' of the 1930s was one of football's first great sides. The modern team qualified impressively and features Bundesliga-quality players. David Alaba's experience is central, and Marcel Sabitzer provides dynamic midfield energy. They can cause upsets.", trivia:"Austria's Wunderteam of the 1930s, coached by Hugo Meisl, played the first-ever international match under floodlights." },
  jordan:       { name:"Jordan",        flag:"🇯🇴", group:"J", colors:["#007A3D","#CE1126"], fifa_rank:74, pop:"10.2M", cap:"Amman", founded:1949, wc_apps:1, best:"World Cup Debut (2026)", bio:"Jordan makes their stunning World Cup debut — arguably Asia's biggest footballing story of 2026. Reaching the Asian Cup final in 2023, the Nashama ('Brave Ones') play fearless, attacking football under expert coaching. Mousa Al-Tamari's creativity is their major weapon.", trivia:"Jordan reached the 2023 Asian Cup final, their greatest-ever achievement, losing 1-0 to Qatar." },
  // GROUP K
  portugal:     { name:"Portugal",      flag:"🇵🇹", group:"K", colors:["#006600","#FF0000"], fifa_rank:8, pop:"10.3M", cap:"Lisbon", founded:1914, wc_apps:9, best:"3rd Place (1966), Semi-finals (2006, 2022)", bio:"Cristiano Ronaldo's farewell? At 41, he will likely play his final World Cup with the hunger of a man who wants one more achievement. Bruno Fernandes and Rafael Leão provide elite quality around him. Portugal have the squad to go deep — the question is mental pressure.", trivia:"Eusébio scored 9 goals for Portugal at the 1966 World Cup, a record that stood for 24 years." },
  dr_congo:     { name:"DR Congo",      flag:"🇨🇩", group:"K", colors:["#007FFF","#F7D918"], fifa_rank:69, pop:"100M", cap:"Kinshasa", founded:1919, wc_apps:2, best:"Quarterfinals (1974) as Zaire", bio:"One of Africa's giants finally returns after 52 years. The Leopards as Zaire were memorably chaotic in 1974, but today's DR Congo squad features technically gifted players from European leagues. Silas and Yannick Bolasie bring Premier League pedigree.", trivia:"Zaire (now DR Congo) holds the record for the biggest defeat in a World Cup group match — 9-0 vs Yugoslavia in 1974." },
  uzbekistan:   { name:"Uzbekistan",    flag:"🇺🇿", group:"K", colors:["#1EB53A","#FFFFFF"], fifa_rank:61, pop:"35M",  cap:"Tashkent", founded:1992, wc_apps:1, best:"World Cup Debut (2026)", bio:"Central Asia's football revolution reaches its peak. Uzbekistan's 'White Wolves' qualified for their first World Cup with an unbeaten run through the AFC. Their technically skilled players — many developed through European academies — bring fresh energy to the tournament. A debut to celebrate.", trivia:"Uzbekistan went unbeaten throughout their 2026 World Cup qualification campaign, setting a new AFC record." },
  colombia:     { name:"Colombia",      flag:"🇨🇴", group:"K", colors:["#FCD116","#003087"], fifa_rank:19, pop:"51M",  cap:"Bogotá", founded:1924, wc_apps:7, best:"Quarterfinals (2014)", bio:"Colombia's 2014 run featured James Rodríguez's Golden Boot. Luis Díaz and Jhon Córdoba lead a new generation of players excelling in Europe. Under their dynamic coach, Colombia play high-energy pressing football with technical brilliance. They enter 2026 as genuine dark horses.", trivia:"James Rodríguez scored the goal of the tournament at 2014 WC — a stunning volley against Uruguay in the Round of 16." },
  // GROUP L
  england:      { name:"England",       flag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", group:"L", colors:["#CF081F","#FFFFFF"], fifa_rank:4, pop:"56M",   cap:"London", founded:1863, wc_apps:17, best:"Winners (1966)", bio:"'It's coming home'... still waiting since 1966. Jude Bellingham, Bukayo Saka, Phil Foden, and Harry Kane make this England's most talented squad in a generation. Their Euro 2024 final appearance showed real progress. 2026 may finally be the year England's hurt ends — or deepens.", trivia:"England's 1966 World Cup win at Wembley remains their only major international trophy in 60 years." },
  croatia:      { name:"Croatia",       flag:"🇭🇷", group:"L", colors:["#FF0000","#FFFFFF"], fifa_rank:10, pop:"4M",   cap:"Zagreb", founded:1912, wc_apps:7, best:"Runner-up (2018), 3rd Place (2022)", bio:"Two consecutive top-3 finishes show Croatia's remarkable consistency for a country of 4 million. Luka Modrić at 41 brings one last magical chapter. Modrić's vision, Kovačić's energy, and Gvardiol's defensive excellence make them tournament veterans who know how to win knockout football.", trivia:"Croatia's Luka Modrić won the Golden Ball at 2018 WC aged 32, becoming the first non-European or South American to win it since 1978." },
  ghana:        { name:"Ghana",         flag:"🇬🇭", group:"L", colors:["#006B3F","#FCD116"], fifa_rank:65, pop:"32M",  cap:"Accra", founded:1957, wc_apps:4, best:"Quarterfinals (2010)", bio:"The Black Stars were one kick from the World Cup semi-finals in 2010 — Asamoah Gyan's penalty miss still haunts them. Jordan Ayew and Mohammed Kudus lead a team with genuine Premier League quality throughout. Ghana are never easy to beat and always exciting to watch.", trivia:"Ghana's Luis Suárez handball moment vs Uruguay in 2010 is one of the most controversial incidents in World Cup history." },
  panama:       { name:"Panama",        flag:"🇵🇦", group:"L", colors:["#DA121A","#003893"], fifa_rank:82, pop:"4.4M", cap:"Panama City", founded:1937, wc_apps:2, best:"Group Stage (2018)", bio:"Panama shocked the world by qualifying in 2018 and made their debut at 54 years old. Rolando Blackburn and Cecilio Waterman lead a team built on togetherness and physical resilience. Panama's qualifying record through CONCACAF deserves massive respect.", trivia:"Panama's Román Torres scored their first-ever World Cup qualifying goal in the dying minutes to book their 2018 berth." },
};

// ============================================================
//  COMPLETE MATCH SCHEDULE (72 Group + 32 Knockout = 104)
// ============================================================
const MATCHES = [
  // ====== GROUP A ======
  { id:"A1", grp:"A", home:"mexico",      away:"south_africa", utc:"2026-06-11T19:00:00Z", venue:"Mexico City Stadium",            hs:2, as:0, st:"FT" },
  { id:"A2", grp:"A", home:"south_korea", away:"czechia",      utc:"2026-06-12T02:00:00Z", venue:"Estadio Guadalajara, Zapopan",    hs:2, as:1, st:"FT" },
  { id:"A3", grp:"A", home:"czechia",     away:"south_africa", utc:"2026-06-18T16:00:00Z", venue:"Atlanta Stadium",                 hs:null, as:null, st:"NS" },
  { id:"A4", grp:"A", home:"mexico",      away:"south_korea",  utc:"2026-06-19T01:00:00Z", venue:"Estadio Guadalajara, Zapopan",    hs:null, as:null, st:"NS" },
  { id:"A5", grp:"A", home:"czechia",     away:"mexico",       utc:"2026-06-25T01:00:00Z", venue:"Mexico City Stadium",             hs:null, as:null, st:"NS" },
  { id:"A6", grp:"A", home:"south_africa",away:"south_korea",  utc:"2026-06-25T01:00:00Z", venue:"Estadio Monterrey, Guadalupe",    hs:null, as:null, st:"NS" },
  // ====== GROUP B ======
  { id:"B1", grp:"B", home:"canada",      away:"bosnia",       utc:"2026-06-12T19:00:00Z", venue:"Toronto Stadium",                 hs:null, as:null, st:"NS" },
  { id:"B2", grp:"B", home:"qatar",       away:"switzerland",  utc:"2026-06-13T19:00:00Z", venue:"San Francisco Bay Area Stadium",  hs:null, as:null, st:"NS" },
  { id:"B3", grp:"B", home:"switzerland", away:"bosnia",       utc:"2026-06-18T19:00:00Z", venue:"Los Angeles Stadium",             hs:null, as:null, st:"NS" },
  { id:"B4", grp:"B", home:"canada",      away:"qatar",        utc:"2026-06-18T22:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS" },
  { id:"B5", grp:"B", home:"switzerland", away:"canada",       utc:"2026-06-24T19:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS" },
  { id:"B6", grp:"B", home:"bosnia",      away:"qatar",        utc:"2026-06-24T19:00:00Z", venue:"Seattle Stadium",                 hs:null, as:null, st:"NS" },
  // ====== GROUP C ======
  { id:"C1", grp:"C", home:"brazil",      away:"morocco",      utc:"2026-06-13T22:00:00Z", venue:"New York New Jersey Stadium",     hs:null, as:null, st:"NS" },
  { id:"C2", grp:"C", home:"haiti",       away:"scotland",     utc:"2026-06-14T01:00:00Z", venue:"Boston Stadium",                  hs:null, as:null, st:"NS" },
  { id:"C3", grp:"C", home:"scotland",    away:"morocco",      utc:"2026-06-19T22:00:00Z", venue:"Boston Stadium",                  hs:null, as:null, st:"NS" },
  { id:"C4", grp:"C", home:"brazil",      away:"haiti",        utc:"2026-06-20T00:30:00Z", venue:"Philadelphia Stadium",            hs:null, as:null, st:"NS" },
  { id:"C5", grp:"C", home:"scotland",    away:"brazil",       utc:"2026-06-24T22:00:00Z", venue:"Miami Stadium",                   hs:null, as:null, st:"NS" },
  { id:"C6", grp:"C", home:"morocco",     away:"haiti",        utc:"2026-06-24T22:00:00Z", venue:"Atlanta Stadium",                 hs:null, as:null, st:"NS" },
  // ====== GROUP D ======
  { id:"D1", grp:"D", home:"usa",         away:"paraguay",     utc:"2026-06-13T01:00:00Z", venue:"Los Angeles Stadium",             hs:null, as:null, st:"NS" },
  { id:"D2", grp:"D", home:"australia",   away:"turkiye",      utc:"2026-06-14T04:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS" },
  { id:"D3", grp:"D", home:"usa",         away:"australia",    utc:"2026-06-19T19:00:00Z", venue:"Seattle Stadium",                 hs:null, as:null, st:"NS" },
  { id:"D4", grp:"D", home:"turkiye",     away:"paraguay",     utc:"2026-06-20T03:00:00Z", venue:"San Francisco Bay Area Stadium",  hs:null, as:null, st:"NS" },
  { id:"D5", grp:"D", home:"turkiye",     away:"usa",          utc:"2026-06-26T02:00:00Z", venue:"Los Angeles Stadium",             hs:null, as:null, st:"NS" },
  { id:"D6", grp:"D", home:"paraguay",    away:"australia",    utc:"2026-06-26T02:00:00Z", venue:"San Francisco Bay Area Stadium",  hs:null, as:null, st:"NS" },
  // ====== GROUP E ======
  { id:"E1", grp:"E", home:"germany",     away:"curacao",      utc:"2026-06-14T17:00:00Z", venue:"Houston Stadium",                 hs:null, as:null, st:"NS" },
  { id:"E2", grp:"E", home:"ivory_coast", away:"ecuador",      utc:"2026-06-14T23:00:00Z", venue:"Philadelphia Stadium",            hs:null, as:null, st:"NS" },
  { id:"E3", grp:"E", home:"germany",     away:"ivory_coast",  utc:"2026-06-20T20:00:00Z", venue:"Toronto Stadium",                 hs:null, as:null, st:"NS" },
  { id:"E4", grp:"E", home:"ecuador",     away:"curacao",      utc:"2026-06-21T03:00:00Z", venue:"Kansas City Stadium",             hs:null, as:null, st:"NS" },
  { id:"E5", grp:"E", home:"ecuador",     away:"germany",      utc:"2026-06-25T20:00:00Z", venue:"New York New Jersey Stadium",     hs:null, as:null, st:"NS" },
  { id:"E6", grp:"E", home:"curacao",     away:"ivory_coast",  utc:"2026-06-25T20:00:00Z", venue:"Philadelphia Stadium",            hs:null, as:null, st:"NS" },
  // ====== GROUP F ======
  { id:"F1", grp:"F", home:"netherlands", away:"japan",        utc:"2026-06-14T20:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS" },
  { id:"F2", grp:"F", home:"sweden",      away:"tunisia",      utc:"2026-06-15T02:00:00Z", venue:"Estadio Monterrey, Guadalupe",    hs:null, as:null, st:"NS" },
  { id:"F3", grp:"F", home:"netherlands", away:"sweden",       utc:"2026-06-20T17:00:00Z", venue:"Houston Stadium",                 hs:null, as:null, st:"NS" },
  { id:"F4", grp:"F", home:"tunisia",     away:"japan",        utc:"2026-06-21T04:00:00Z", venue:"Estadio Monterrey, Guadalupe",    hs:null, as:null, st:"NS" },
  { id:"F5", grp:"F", home:"japan",       away:"sweden",       utc:"2026-06-25T23:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS" },
  { id:"F6", grp:"F", home:"tunisia",     away:"netherlands",  utc:"2026-06-25T23:00:00Z", venue:"Kansas City Stadium",             hs:null, as:null, st:"NS" },
  // ====== GROUP G ======
  { id:"G1", grp:"G", home:"belgium",     away:"egypt",        utc:"2026-06-15T19:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS" },
  { id:"G2", grp:"G", home:"iran",        away:"new_zealand",  utc:"2026-06-16T01:00:00Z", venue:"Los Angeles Stadium",             hs:null, as:null, st:"NS" },
  { id:"G3", grp:"G", home:"belgium",     away:"iran",         utc:"2026-06-21T19:00:00Z", venue:"Los Angeles Stadium",             hs:null, as:null, st:"NS" },
  { id:"G4", grp:"G", home:"new_zealand", away:"egypt",        utc:"2026-06-22T01:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS" },
  { id:"G5", grp:"G", home:"egypt",       away:"iran",         utc:"2026-06-27T03:00:00Z", venue:"Seattle Stadium",                 hs:null, as:null, st:"NS" },
  { id:"G6", grp:"G", home:"new_zealand", away:"belgium",      utc:"2026-06-27T03:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS" },
  // ====== GROUP H ======
  { id:"H1", grp:"H", home:"spain",       away:"cape_verde",   utc:"2026-06-15T16:00:00Z", venue:"Atlanta Stadium",                 hs:null, as:null, st:"NS" },
  { id:"H2", grp:"H", home:"saudi_arabia",away:"uruguay",      utc:"2026-06-15T22:00:00Z", venue:"Miami Stadium",                   hs:null, as:null, st:"NS" },
  { id:"H3", grp:"H", home:"spain",       away:"saudi_arabia", utc:"2026-06-21T16:00:00Z", venue:"Atlanta Stadium",                 hs:null, as:null, st:"NS" },
  { id:"H4", grp:"H", home:"uruguay",     away:"cape_verde",   utc:"2026-06-21T22:00:00Z", venue:"Miami Stadium",                   hs:null, as:null, st:"NS" },
  { id:"H5", grp:"H", home:"cape_verde",  away:"saudi_arabia", utc:"2026-06-27T00:00:00Z", venue:"Houston Stadium",                 hs:null, as:null, st:"NS" },
  { id:"H6", grp:"H", home:"uruguay",     away:"spain",        utc:"2026-06-27T00:00:00Z", venue:"Estadio Guadalajara, Zapopan",    hs:null, as:null, st:"NS" },
  // ====== GROUP I ======
  { id:"I1", grp:"I", home:"france",      away:"senegal",      utc:"2026-06-16T19:00:00Z", venue:"New York New Jersey Stadium",     hs:null, as:null, st:"NS" },
  { id:"I2", grp:"I", home:"iraq",        away:"norway",       utc:"2026-06-16T22:00:00Z", venue:"Boston Stadium",                  hs:null, as:null, st:"NS" },
  { id:"I3", grp:"I", home:"france",      away:"iraq",         utc:"2026-06-22T21:00:00Z", venue:"Philadelphia Stadium",            hs:null, as:null, st:"NS" },
  { id:"I4", grp:"I", home:"norway",      away:"senegal",      utc:"2026-06-23T00:00:00Z", venue:"New York New Jersey Stadium",     hs:null, as:null, st:"NS" },
  { id:"I5", grp:"I", home:"norway",      away:"france",       utc:"2026-06-26T19:00:00Z", venue:"Boston Stadium",                  hs:null, as:null, st:"NS" },
  { id:"I6", grp:"I", home:"senegal",     away:"iraq",         utc:"2026-06-26T19:00:00Z", venue:"Toronto Stadium",                 hs:null, as:null, st:"NS" },
  // ====== GROUP J ======
  { id:"J1", grp:"J", home:"argentina",   away:"algeria",      utc:"2026-06-17T01:00:00Z", venue:"Kansas City Stadium",             hs:null, as:null, st:"NS" },
  { id:"J2", grp:"J", home:"austria",     away:"jordan",       utc:"2026-06-17T04:00:00Z", venue:"San Francisco Bay Area Stadium",  hs:null, as:null, st:"NS" },
  { id:"J3", grp:"J", home:"argentina",   away:"austria",      utc:"2026-06-22T17:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS" },
  { id:"J4", grp:"J", home:"jordan",      away:"algeria",      utc:"2026-06-23T03:00:00Z", venue:"San Francisco Bay Area Stadium",  hs:null, as:null, st:"NS" },
  { id:"J5", grp:"J", home:"algeria",     away:"austria",      utc:"2026-06-28T02:00:00Z", venue:"Kansas City Stadium",             hs:null, as:null, st:"NS" },
  { id:"J6", grp:"J", home:"jordan",      away:"argentina",    utc:"2026-06-28T02:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS" },
  // ====== GROUP K ======
  { id:"K1", grp:"K", home:"portugal",    away:"dr_congo",     utc:"2026-06-17T17:00:00Z", venue:"Houston Stadium",                 hs:null, as:null, st:"NS" },
  { id:"K2", grp:"K", home:"uzbekistan",  away:"colombia",     utc:"2026-06-18T02:00:00Z", venue:"Mexico City Stadium",             hs:null, as:null, st:"NS" },
  { id:"K3", grp:"K", home:"portugal",    away:"uzbekistan",   utc:"2026-06-23T17:00:00Z", venue:"Houston Stadium",                 hs:null, as:null, st:"NS" },
  { id:"K4", grp:"K", home:"colombia",    away:"dr_congo",     utc:"2026-06-24T02:00:00Z", venue:"Estadio Guadalajara, Zapopan",    hs:null, as:null, st:"NS" },
  { id:"K5", grp:"K", home:"colombia",    away:"portugal",     utc:"2026-06-27T23:30:00Z", venue:"Miami Stadium",                   hs:null, as:null, st:"NS" },
  { id:"K6", grp:"K", home:"dr_congo",    away:"uzbekistan",   utc:"2026-06-27T23:30:00Z", venue:"Atlanta Stadium",                 hs:null, as:null, st:"NS" },
  // ====== GROUP L ======
  { id:"L1", grp:"L", home:"england",     away:"croatia",      utc:"2026-06-17T20:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS" },
  { id:"L2", grp:"L", home:"ghana",       away:"panama",       utc:"2026-06-17T23:00:00Z", venue:"Toronto Stadium",                 hs:null, as:null, st:"NS" },
  { id:"L3", grp:"L", home:"england",     away:"ghana",        utc:"2026-06-23T20:00:00Z", venue:"Boston Stadium",                  hs:null, as:null, st:"NS" },
  { id:"L4", grp:"L", home:"panama",      away:"croatia",      utc:"2026-06-23T23:00:00Z", venue:"Toronto Stadium",                 hs:null, as:null, st:"NS" },
  { id:"L5", grp:"L", home:"panama",      away:"england",      utc:"2026-06-27T21:00:00Z", venue:"New York New Jersey Stadium",     hs:null, as:null, st:"NS" },
  { id:"L6", grp:"L", home:"croatia",     away:"ghana",        utc:"2026-06-27T21:00:00Z", venue:"Philadelphia Stadium",            hs:null, as:null, st:"NS" },
  // ====== ROUND OF 32 (TBD) ======
  { id:"R32-1",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-06-28T19:00:00Z", venue:"Los Angeles Stadium",             hs:null, as:null, st:"NS", label:"R32-1:  1A vs 3C/E/F/H/I" },
  { id:"R32-2",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-06-29T19:00:00Z", venue:"Houston Stadium",                 hs:null, as:null, st:"NS", label:"R32-2:  1B vs 3A/C/D/G" },
  { id:"R32-3",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-06-29T20:30:00Z", venue:"Boston Stadium",                  hs:null, as:null, st:"NS", label:"R32-3:  2A vs 2B" },
  { id:"R32-4",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-06-30T01:00:00Z", venue:"Estadio Monterrey",               hs:null, as:null, st:"NS", label:"R32-4:  1C vs 3A/B/D/H/K/L" },
  { id:"R32-5",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-06-30T17:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS", label:"R32-5:  1D vs 3C/E/F/H/I" },
  { id:"R32-6",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-06-30T21:00:00Z", venue:"New York New Jersey Stadium",     hs:null, as:null, st:"NS", label:"R32-6:  2C vs 2D" },
  { id:"R32-7",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-01T01:00:00Z", venue:"Mexico City Stadium",             hs:null, as:null, st:"NS", label:"R32-7:  1E vs 3D/F/G/J/K" },
  { id:"R32-8",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-01T16:00:00Z", venue:"Atlanta Stadium",                 hs:null, as:null, st:"NS", label:"R32-8:  1F vs 3A/B/D/H/K/L" },
  { id:"R32-9",  grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-01T20:00:00Z", venue:"Seattle Stadium",                 hs:null, as:null, st:"NS", label:"R32-9:  2E vs 2F" },
  { id:"R32-10", grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-01T20:00:00Z", venue:"San Francisco Bay Area Stadium",  hs:null, as:null, st:"NS", label:"R32-10: 1G vs 3D/E/F/I/K" },
  { id:"R32-11", grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-02T19:00:00Z", venue:"Los Angeles Stadium",             hs:null, as:null, st:"NS", label:"R32-11: 1H vs 3A/B/G/J/L" },
  { id:"R32-12", grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-02T23:00:00Z", venue:"Toronto Stadium",                 hs:null, as:null, st:"NS", label:"R32-12: 2G vs 2H" },
  { id:"R32-13", grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-03T03:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS", label:"R32-13: 1I vs 3B/D/E/G/J" },
  { id:"R32-14", grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-03T18:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS", label:"R32-14: 2I vs 2J" },
  { id:"R32-15", grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-03T22:00:00Z", venue:"Miami Stadium",                   hs:null, as:null, st:"NS", label:"R32-15: 1J vs 3F/G/H/I/K/L" },
  { id:"R32-16", grp:"R32", home:"tbd", away:"tbd", utc:"2026-07-04T01:30:00Z", venue:"Kansas City Stadium",             hs:null, as:null, st:"NS", label:"R32-16: 2K vs 2L" },
  // ====== ROUND OF 16 (TBD) ======
  { id:"R16-1", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-04T17:00:00Z", venue:"Houston Stadium",                 hs:null, as:null, st:"NS", label:"R16-1: Winner R32-1 vs Winner R32-2" },
  { id:"R16-2", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-04T21:00:00Z", venue:"Philadelphia Stadium",            hs:null, as:null, st:"NS", label:"R16-2: Winner R32-3 vs Winner R32-4" },
  { id:"R16-3", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-05T20:00:00Z", venue:"New York New Jersey Stadium",     hs:null, as:null, st:"NS", label:"R16-3: Winner R32-5 vs Winner R32-6" },
  { id:"R16-4", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-06T00:00:00Z", venue:"Mexico City Stadium",             hs:null, as:null, st:"NS", label:"R16-4: Winner R32-7 vs Winner R32-8" },
  { id:"R16-5", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-06T19:00:00Z", venue:"Dallas Stadium",                  hs:null, as:null, st:"NS", label:"R16-5: Winner R32-9 vs Winner R32-10" },
  { id:"R16-6", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-07T00:00:00Z", venue:"Seattle Stadium",                 hs:null, as:null, st:"NS", label:"R16-6: Winner R32-11 vs Winner R32-12" },
  { id:"R16-7", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-07T16:00:00Z", venue:"Atlanta Stadium",                 hs:null, as:null, st:"NS", label:"R16-7: Winner R32-13 vs Winner R32-14" },
  { id:"R16-8", grp:"R16", home:"tbd", away:"tbd", utc:"2026-07-07T20:00:00Z", venue:"BC Place, Vancouver",             hs:null, as:null, st:"NS", label:"R16-8: Winner R32-15 vs Winner R32-16" },
  // ====== QUARTERFINALS ======
  { id:"QF1", grp:"QF", home:"tbd", away:"tbd", utc:"2026-07-09T20:00:00Z", venue:"Boston Stadium",              hs:null, as:null, st:"NS", label:"QF1: Winner R16-1 vs Winner R16-2" },
  { id:"QF2", grp:"QF", home:"tbd", away:"tbd", utc:"2026-07-10T19:00:00Z", venue:"Los Angeles Stadium",         hs:null, as:null, st:"NS", label:"QF2: Winner R16-3 vs Winner R16-4" },
  { id:"QF3", grp:"QF", home:"tbd", away:"tbd", utc:"2026-07-11T20:00:00Z", venue:"Miami Stadium",               hs:null, as:null, st:"NS", label:"QF3: Winner R16-5 vs Winner R16-6" },
  { id:"QF4", grp:"QF", home:"tbd", away:"tbd", utc:"2026-07-12T01:00:00Z", venue:"Kansas City Stadium",         hs:null, as:null, st:"NS", label:"QF4: Winner R16-7 vs Winner R16-8" },
  // ====== SEMIFINALS ======
  { id:"SF1", grp:"SF", home:"tbd", away:"tbd", utc:"2026-07-14T19:00:00Z", venue:"Dallas Stadium",              hs:null, as:null, st:"NS", label:"SF1: Winner QF1 vs Winner QF2" },
  { id:"SF2", grp:"SF", home:"tbd", away:"tbd", utc:"2026-07-15T19:00:00Z", venue:"Atlanta Stadium",             hs:null, as:null, st:"NS", label:"SF2: Winner QF3 vs Winner QF4" },
  // ====== BRONZE & FINAL ======
  { id:"BM",  grp:"3P", home:"tbd", away:"tbd", utc:"2026-07-18T21:00:00Z", venue:"Miami Stadium",               hs:null, as:null, st:"NS", label:"3rd Place: Loser SF1 vs Loser SF2" },
  { id:"FIN", grp:"FIN", home:"tbd", away:"tbd", utc:"2026-07-19T19:00:00Z", venue:"New York New Jersey Stadium", hs:null, as:null, st:"NS", label:"FINAL: Winner SF1 vs Winner SF2" },
];

// ============================================================
//  PLAYER SQUADS
//  GK: { n, p:"GK", ag, cl, sv, ca, r }
//  FP: { n, p, ag, cl, g, as, ca, r }
//  p = GK/DEF/MID/FWD, ca=caps, r=EA FC rating
// ============================================================
const PLAYERS = {
  argentina: [
    { n:"Emiliano Martínez",    p:"GK",  ag:33, cl:"Aston Villa",        sv:142, ca:68,  r:88 },
    { n:"Geronimo Rulli",       p:"GK",  ag:33, cl:"Atlético Madrid",    sv:88,  ca:17,  r:82 },
    { n:"Juan Musso",           p:"GK",  ag:30, cl:"Atletico Madrid",    sv:96,  ca:22,  r:81 },
    { n:"Nicolás Otamendi",     p:"DEF", ag:36, cl:"Benfica",           g:4,    as:1,   ca:108, r:82 },
    { n:"Cristian Romero",      p:"DEF", ag:26, cl:"Tottenham",         g:7,    as:5,   ca:42,  r:86 },
    { n:"Nicolás Tagliafico",   p:"DEF", ag:31, cl:"Lyon",              g:3,    as:8,   ca:63,  r:81 },
    { n:"Germán Pezzella",      p:"DEF", ag:33, cl:"Real Betis",        g:3,    as:1,   ca:43,  r:79 },
    { n:"Marcos Acuña",         p:"DEF", ag:32, cl:"Sevilla",           g:5,    as:14,  ca:66,  r:80 },
    { n:"Nahuel Molina",        p:"DEF", ag:26, cl:"Atletico Madrid",   g:6,    as:9,   ca:47,  r:83 },
    { n:"Lisandro Martínez",    p:"DEF", ag:27, cl:"Man United",        g:3,    as:2,   ca:38,  r:85 },
    { n:"Rodrigo De Paul",      p:"MID", ag:30, cl:"Atletico Madrid",   g:15,   as:22,  ca:72,  r:83 },
    { n:"Enzo Fernández",       p:"MID", ag:24, cl:"Chelsea",           g:10,   as:13,  ca:48,  r:85 },
    { n:"Alexis Mac Allister",  p:"MID", ag:25, cl:"Liverpool",         g:14,   as:10,  ca:38,  r:84 },
    { n:"Leandro Paredes",      p:"MID", ag:30, cl:"AS Roma",           g:8,    as:15,  ca:59,  r:82 },
    { n:"Giovani Lo Celso",     p:"MID", ag:28, cl:"Tottenham",         g:12,   as:18,  ca:44,  r:81 },
    { n:"Nicolás González",     p:"MID", ag:26, cl:"Juventus",          g:11,   as:9,   ca:32,  r:80 },
    { n:"Lionel Messi",         p:"FWD", ag:38, cl:"Inter Miami",       g:106,  as:58,  ca:191, r:89 },
    { n:"Julián Álvarez",       p:"FWD", ag:24, cl:"Atletico Madrid",   g:18,   as:9,   ca:43,  r:87 },
    { n:"Lautaro Martínez",     p:"FWD", ag:27, cl:"Inter Milan",       g:30,   as:11,  ca:60,  r:85 },
    { n:"Angel Di María",       p:"FWD", ag:38, cl:"Benfica",           g:31,   as:31,  ca:145, r:80 },
    { n:"Paulo Dybala",         p:"FWD", ag:31, cl:"AS Roma",           g:22,   as:16,  ca:52,  r:84 },
    { n:"Thiago Almada",        p:"MID", ag:23, cl:"Lyon",              g:7,    as:10,  ca:22,  r:79 },
    { n:"Valentín Carboni",     p:"FWD", ag:20, cl:"Inter Milan",       g:2,    as:4,   ca:8,   r:77 },
  ],
  brazil: [
    { n:"Alisson Becker",       p:"GK",  ag:33, cl:"Liverpool",         sv:168, ca:82,  r:90 },
    { n:"Ederson",              p:"GK",  ag:31, cl:"Man City",          sv:124, ca:42,  r:87 },
    { n:"Weverton",             p:"GK",  ag:36, cl:"Palmeiras",         sv:98,  ca:32,  r:80 },
    { n:"Marquinhos",           p:"DEF", ag:31, cl:"PSG",               g:14,   as:6,   ca:88,  r:86 },
    { n:"Gabriel Magalhães",    p:"DEF", ag:27, cl:"Arsenal",           g:12,   as:3,   ca:32,  r:84 },
    { n:"Éder Militão",         p:"DEF", ag:27, cl:"Real Madrid",       g:6,    as:2,   ca:42,  r:84 },
    { n:"Alex Sandro",          p:"DEF", ag:34, cl:"Juventus",          g:8,    as:22,  ca:64,  r:79 },
    { n:"Danilo",               p:"DEF", ag:33, cl:"Flamengo",          g:7,    as:15,  ca:57,  r:81 },
    { n:"Alex Telles",          p:"DEF", ag:32, cl:"Sevilla",           g:6,    as:12,  ca:33,  r:79 },
    { n:"Casemiro",             p:"MID", ag:34, cl:"Man United",        g:18,   as:16,  ca:83,  r:85 },
    { n:"Lucas Paquetá",        p:"MID", ag:27, cl:"West Ham",          g:14,   as:18,  ca:54,  r:84 },
    { n:"Bruno Guimarães",      p:"MID", ag:27, cl:"Newcastle",         g:11,   as:15,  ca:42,  r:84 },
    { n:"Gerson",               p:"MID", ag:27, cl:"Flamengo",          g:12,   as:14,  ca:22,  r:81 },
    { n:"Andreas Pereira",      p:"MID", ag:29, cl:"Fulham",            g:8,    as:14,  ca:23,  r:80 },
    { n:"Vinicius Jr",          p:"FWD", ag:25, cl:"Real Madrid",       g:44,   as:28,  ca:72,  r:93 },
    { n:"Rodrygo",              p:"FWD", ag:24, cl:"Real Madrid",       g:22,   as:18,  ca:38,  r:85 },
    { n:"Endrick",              p:"FWD", ag:18, cl:"Real Madrid",       g:8,    as:4,   ca:18,  r:82 },
    { n:"Richarlison",          p:"FWD", ag:28, cl:"Tottenham",         g:22,   as:9,   ca:56,  r:83 },
    { n:"Gabriel Martinelli",   p:"FWD", ag:23, cl:"Arsenal",           g:14,   as:12,  ca:22,  r:83 },
    { n:"Raphinha",             p:"FWD", ag:28, cl:"Barcelona",         g:22,   as:18,  ca:52,  r:84 },
    { n:"Gabriel Jesus",        p:"FWD", ag:28, cl:"Arsenal",           g:18,   as:11,  ca:68,  r:83 },
    { n:"Matheus Cunha",        p:"FWD", ag:26, cl:"Wolves",            g:16,   as:14,  ca:28,  r:82 },
    { n:"Matheus Nunes",        p:"MID", ag:26, cl:"Man City",          g:6,    as:11,  ca:18,  r:81 },
  ],
  france: [
    { n:"Mike Maignan",         p:"GK",  ag:29, cl:"AC Milan",          sv:138, ca:28,  r:87 },
    { n:"Alphonse Areola",      p:"GK",  ag:31, cl:"West Ham",          sv:96,  ca:14,  r:81 },
    { n:"Brice Samba",          p:"GK",  ag:30, cl:"RC Lens",           sv:112, ca:6,   r:80 },
    { n:"William Saliba",       p:"DEF", ag:24, cl:"Arsenal",           g:3,    as:2,   ca:22,  r:85 },
    { n:"Dayot Upamecano",      p:"DEF", ag:26, cl:"Bayern Munich",     g:4,    as:1,   ca:28,  r:84 },
    { n:"Jules Koundé",         p:"DEF", ag:26, cl:"Barcelona",         g:4,    as:5,   ca:38,  r:84 },
    { n:"Ibrahima Konaté",      p:"DEF", ag:26, cl:"Liverpool",         g:2,    as:1,   ca:18,  r:83 },
    { n:"Theo Hernández",       p:"DEF", ag:27, cl:"AC Milan",          g:8,    as:14,  ca:38,  r:85 },
    { n:"Lucas Hernández",      p:"DEF", ag:28, cl:"Paris SG",          g:3,    as:4,   ca:52,  r:82 },
    { n:"Adrien Rabiot",        p:"MID", ag:30, cl:"Juventus",          g:12,   as:11,  ca:51,  r:83 },
    { n:"Aurélien Tchouaméni",  p:"MID", ag:25, cl:"Real Madrid",       g:8,    as:6,   ca:32,  r:84 },
    { n:"Eduardo Camavinga",    p:"MID", ag:22, cl:"Real Madrid",       g:4,    as:8,   ca:28,  r:84 },
    { n:"Youssouf Fofana",      p:"MID", ag:25, cl:"AC Milan",          g:5,    as:7,   ca:14,  r:81 },
    { n:"N'Golo Kanté",         p:"MID", ag:33, cl:"Al-Ittihad",        g:6,    as:8,   ca:56,  r:85 },
    { n:"Kylian Mbappé",        p:"FWD", ag:27, cl:"Real Madrid",       g:62,   as:31,  ca:82,  r:93 },
    { n:"Antoine Griezmann",    p:"FWD", ag:35, cl:"Atletico Madrid",   g:50,   as:33,  ca:132, r:85 },
    { n:"Ousmane Dembélé",      p:"FWD", ag:28, cl:"PSG",               g:18,   as:22,  ca:48,  r:85 },
    { n:"Marcus Thuram",        p:"FWD", ag:27, cl:"Inter Milan",       g:18,   as:10,  ca:28,  r:84 },
    { n:"Randal Kolo Muani",    p:"FWD", ag:26, cl:"PSG",               g:12,   as:8,   ca:22,  r:82 },
    { n:"Jonathan Clauss",      p:"DEF", ag:32, cl:"Marseille",         g:4,    as:14,  ca:22,  r:80 },
    { n:"Benjamin Pavard",      p:"DEF", ag:28, cl:"Inter Milan",       g:8,    as:9,   ca:60,  r:83 },
    { n:"Kingsley Coman",       p:"FWD", ag:29, cl:"Bayern Munich",     g:12,   as:14,  ca:52,  r:83 },
    { n:"Michael Olise",        p:"FWD", ag:23, cl:"Bayern Munich",     g:8,    as:10,  ca:12,  r:83 },
  ],
  england: [
    { n:"Jordan Pickford",      p:"GK",  ag:32, cl:"Everton",           sv:136, ca:68,  r:83 },
    { n:"Nick Pope",            p:"GK",  ag:32, cl:"Newcastle",         sv:118, ca:12,  r:82 },
    { n:"Aaron Ramsdale",       p:"GK",  ag:26, cl:"Southampton",       sv:94,  ca:8,   r:81 },
    { n:"Trent Alexander-Arnold",p:"DEF",ag:27, cl:"Real Madrid",       g:8,    as:22,  ca:38,  r:85 },
    { n:"Reece James",          p:"DEF", ag:25, cl:"Chelsea",           g:6,    as:14,  ca:22,  r:84 },
    { n:"Harry Maguire",        p:"DEF", ag:31, cl:"Man United",        g:10,   as:3,   ca:63,  r:80 },
    { n:"John Stones",          p:"DEF", ag:31, cl:"Man City",          g:6,    as:4,   ca:72,  r:83 },
    { n:"Luke Shaw",            p:"DEF", ag:29, cl:"Man United",        g:2,    as:8,   ca:38,  r:82 },
    { n:"Kieran Trippier",      p:"DEF", ag:34, cl:"Newcastle",         g:8,    as:18,  ca:54,  r:83 },
    { n:"Marc Guéhi",           p:"DEF", ag:24, cl:"Crystal Palace",    g:3,    as:2,   ca:18,  r:80 },
    { n:"Declan Rice",          p:"MID", ag:26, cl:"Arsenal",           g:14,   as:18,  ca:52,  r:86 },
    { n:"Jude Bellingham",      p:"MID", ag:21, cl:"Real Madrid",       g:28,   as:16,  ca:38,  r:91 },
    { n:"Phil Foden",           p:"MID", ag:26, cl:"Man City",          g:26,   as:20,  ca:42,  r:87 },
    { n:"Conor Gallagher",      p:"MID", ag:24, cl:"Atletico Madrid",   g:8,    as:12,  ca:22,  r:81 },
    { n:"Kobbie Mainoo",        p:"MID", ag:19, cl:"Man United",        g:4,    as:8,   ca:12,  r:79 },
    { n:"Harry Kane",           p:"FWD", ag:31, cl:"Bayern Munich",     g:68,   as:20,  ca:98,  r:88 },
    { n:"Bukayo Saka",          p:"FWD", ag:23, cl:"Arsenal",           g:28,   as:22,  ca:48,  r:88 },
    { n:"Marcus Rashford",      p:"FWD", ag:27, cl:"Man United",        g:22,   as:12,  ca:58,  r:83 },
    { n:"Raheem Sterling",      p:"FWD", ag:31, cl:"Arsenal",           g:22,   as:18,  ca:84,  r:82 },
    { n:"Jack Grealish",        p:"FWD", ag:30, cl:"Man City",          g:6,    as:12,  ca:37,  r:82 },
    { n:"Jarrod Bowen",         p:"FWD", ag:28, cl:"West Ham",          g:12,   as:14,  ca:22,  r:81 },
    { n:"Cole Palmer",          p:"MID", ag:22, cl:"Chelsea",           g:18,   as:14,  ca:14,  r:85 },
    { n:"Anthony Gordon",       p:"FWD", ag:23, cl:"Newcastle",         g:8,    as:12,  ca:14,  r:80 },
  ],
  germany: [
    { n:"Manuel Neuer",         p:"GK",  ag:39, cl:"Bayern Munich",     sv:188, ca:124, r:87 },
    { n:"Marc-André ter Stegen",p:"GK",  ag:33, cl:"Barcelona",         sv:162, ca:38,  r:86 },
    { n:"Oliver Baumann",       p:"GK",  ag:34, cl:"Hoffenheim",        sv:98,  ca:10,  r:79 },
    { n:"Antonio Rüdiger",      p:"DEF", ag:32, cl:"Real Madrid",       g:14,   as:4,   ca:68,  r:85 },
    { n:"Matthias Ginter",      p:"DEF", ag:31, cl:"Freiburg",          g:10,   as:8,   ca:48,  r:81 },
    { n:"Robin Gosens",         p:"DEF", ag:30, cl:"Inter Milan",       g:12,   as:16,  ca:32,  r:82 },
    { n:"Nico Schlotterbeck",   p:"DEF", ag:25, cl:"Dortmund",          g:4,    as:3,   ca:22,  r:82 },
    { n:"Benjamin Henrichs",    p:"DEF", ag:27, cl:"RB Leipzig",        g:4,    as:10,  ca:22,  r:80 },
    { n:"Joshua Kimmich",       p:"MID", ag:30, cl:"Bayern Munich",     g:18,   as:28,  ca:88,  r:86 },
    { n:"Leon Goretzka",        p:"MID", ag:30, cl:"Bayern Munich",     g:18,   as:22,  ca:52,  r:85 },
    { n:"Toni Kroos",           p:"MID", ag:35, cl:"Real Madrid",       g:17,   as:30,  ca:106, r:86 },
    { n:"Ilkay Gündogan",       p:"MID", ag:36, cl:"Barcelona",         g:18,   as:20,  ca:82,  r:85 },
    { n:"Thomas Müller",        p:"FWD", ag:36, cl:"Bayern Munich",     g:45,   as:48,  ca:131, r:83 },
    { n:"Florian Wirtz",        p:"MID", ag:22, cl:"Bayer Leverkusen",  g:18,   as:22,  ca:22,  r:88 },
    { n:"Jamal Musiala",        p:"MID", ag:22, cl:"Bayern Munich",     g:16,   as:20,  ca:32,  r:87 },
    { n:"Kai Havertz",          p:"FWD", ag:26, cl:"Arsenal",           g:22,   as:14,  ca:54,  r:85 },
    { n:"Leroy Sané",           p:"FWD", ag:29, cl:"Bayern Munich",     g:22,   as:28,  ca:58,  r:85 },
    { n:"Serge Gnabry",         p:"FWD", ag:29, cl:"Bayern Munich",     g:22,   as:18,  ca:44,  r:82 },
    { n:"Niclas Füllkrug",      p:"FWD", ag:32, cl:"Dortmund",          g:12,   as:6,   ca:22,  r:81 },
    { n:"Julian Brandt",        p:"MID", ag:28, cl:"Dortmund",          g:10,   as:18,  ca:48,  r:82 },
    { n:"Deniz Undav",          p:"FWD", ag:28, cl:"Stuttgart",         g:14,   as:12,  ca:14,  r:80 },
    { n:"Angelo Stiller",       p:"MID", ag:23, cl:"Stuttgart",         g:4,    as:8,   ca:10,  r:79 },
    { n:"Maximilian Mittelstädt",p:"DEF",ag:27, cl:"Stuttgart",         g:4,    as:14,  ca:14,  r:79 },
  ],
  spain: [
    { n:"Unai Simón",           p:"GK",  ag:27, cl:"Athletic Bilbao",   sv:128, ca:38,  r:84 },
    { n:"David Raya",           p:"GK",  ag:29, cl:"Arsenal",           sv:118, ca:14,  r:84 },
    { n:"Robert Sánchez",       p:"GK",  ag:27, cl:"Chelsea",           sv:86,  ca:8,   r:80 },
    { n:"Dani Carvajal",        p:"DEF", ag:32, cl:"Real Madrid",       g:6,    as:14,  ca:80,  r:84 },
    { n:"Alejandro Balde",      p:"DEF", ag:21, cl:"Barcelona",         g:4,    as:10,  ca:18,  r:83 },
    { n:"Aymeric Laporte",      p:"DEF", ag:30, cl:"Al-Nassr",          g:8,    as:5,   ca:38,  r:83 },
    { n:"Robin Le Normand",     p:"DEF", ag:28, cl:"Atletico Madrid",   g:4,    as:3,   ca:22,  r:81 },
    { n:"Pau Cubarsí",          p:"DEF", ag:18, cl:"Barcelona",         g:2,    as:2,   ca:10,  r:81 },
    { n:"Jesús Navas",          p:"DEF", ag:39, cl:"Sevilla",           g:4,    as:8,   ca:72,  r:78 },
    { n:"Rodri",                p:"MID", ag:29, cl:"Man City",          g:12,   as:16,  ca:52,  r:89 },
    { n:"Pedri",                p:"MID", ag:23, cl:"Barcelona",         g:8,    as:14,  ca:42,  r:87 },
    { n:"Gavi",                 p:"MID", ag:20, cl:"Barcelona",         g:4,    as:12,  ca:38,  r:87 },
    { n:"Fabián Ruiz",          p:"MID", ag:28, cl:"PSG",               g:8,    as:12,  ca:38,  r:83 },
    { n:"Martín Zubimendi",     p:"MID", ag:25, cl:"Real Sociedad",     g:4,    as:8,   ca:22,  r:83 },
    { n:"Marcos Llorente",      p:"MID", ag:30, cl:"Atletico Madrid",   g:8,    as:14,  ca:34,  r:82 },
    { n:"Álvaro Morata",        p:"FWD", ag:33, cl:"AC Milan",          g:36,   as:14,  ca:72,  r:82 },
    { n:"Lamine Yamal",         p:"FWD", ag:18, cl:"Barcelona",         g:12,   as:14,  ca:18,  r:87 },
    { n:"Nico Williams",        p:"FWD", ag:22, cl:"Athletic Bilbao",   g:10,   as:12,  ca:22,  r:84 },
    { n:"Mikel Oyarzabal",      p:"FWD", ag:28, cl:"Real Sociedad",     g:18,   as:14,  ca:42,  r:83 },
    { n:"Ferran Torres",        p:"FWD", ag:25, cl:"Barcelona",         g:18,   as:10,  ca:42,  r:82 },
    { n:"Joselu",               p:"FWD", ag:34, cl:"Al-Qadsiah",        g:12,   as:6,   ca:24,  r:79 },
    { n:"Bryan Zaragoza",       p:"FWD", ag:23, cl:"Bayern Munich",     g:4,    as:6,   ca:10,  r:79 },
    { n:"Dani Olmo",            p:"MID", ag:26, cl:"Barcelona",         g:10,   as:12,  ca:32,  r:84 },
  ],
  portugal: [
    { n:"Diogo Costa",          p:"GK",  ag:25, cl:"Porto",             sv:118, ca:22,  r:82 },
    { n:"Rui Patrício",         p:"GK",  ag:37, cl:"AS Roma",           sv:138, ca:101, r:80 },
    { n:"José Sá",              p:"GK",  ag:31, cl:"Wolves",            sv:112, ca:16,  r:82 },
    { n:"Rúben Dias",           p:"DEF", ag:28, cl:"Man City",          g:8,    as:4,   ca:48,  r:88 },
    { n:"Pepe",                 p:"DEF", ag:42, cl:"Porto",             g:12,   as:6,   ca:141, r:78 },
    { n:"João Cancelo",         p:"DEF", ag:31, cl:"Barcelona",         g:8,    as:18,  ca:62,  r:85 },
    { n:"Nuno Mendes",          p:"DEF", ag:22, cl:"PSG",               g:4,    as:8,   ca:22,  r:83 },
    { n:"Diogo Dalot",          p:"DEF", ag:26, cl:"Man United",        g:6,    as:12,  ca:32,  r:82 },
    { n:"Danilo Pereira",       p:"DEF", ag:33, cl:"PSG",               g:4,    as:4,   ca:58,  r:80 },
    { n:"Bernardo Silva",       p:"MID", ag:30, cl:"Man City",          g:24,   as:28,  ca:98,  r:87 },
    { n:"Bruno Fernandes",      p:"MID", ag:30, cl:"Man United",        g:28,   as:22,  ca:72,  r:86 },
    { n:"Vitinha",              p:"MID", ag:24, cl:"PSG",               g:6,    as:14,  ca:32,  r:84 },
    { n:"João Neves",           p:"MID", ag:20, cl:"PSG",               g:4,    as:8,   ca:18,  r:82 },
    { n:"Rúben Neves",          p:"MID", ag:28, cl:"Al-Hilal",          g:10,   as:12,  ca:62,  r:83 },
    { n:"Cristiano Ronaldo",    p:"FWD", ag:41, cl:"Al-Nassr",          g:128,  as:30,  ca:212, r:82 },
    { n:"Rafael Leão",          p:"FWD", ag:25, cl:"AC Milan",          g:16,   as:14,  ca:28,  r:85 },
    { n:"Gonçalo Ramos",        p:"FWD", ag:23, cl:"PSG",               g:18,   as:8,   ca:22,  r:83 },
    { n:"Pedro Neto",           p:"FWD", ag:25, cl:"Chelsea",           g:10,   as:14,  ca:32,  r:83 },
    { n:"Diogo Jota",           p:"FWD", ag:28, cl:"Liverpool",         g:22,   as:12,  ca:52,  r:84 },
    { n:"João Félix",           p:"FWD", ag:25, cl:"Chelsea",           g:16,   as:12,  ca:48,  r:83 },
    { n:"Francisco Conceição",  p:"FWD", ag:22, cl:"Juventus",          g:6,    as:8,   ca:12,  r:80 },
    { n:"Nelson Semedo",        p:"DEF", ag:31, cl:"Wolves",            g:2,    as:10,  ca:38,  r:80 },
    { n:"Palhinha",             p:"MID", ag:29, cl:"Bayern Munich",     g:4,    as:4,   ca:28,  r:82 },
  ],
  netherlands: [
    { n:"Bart Verbruggen",      p:"GK",  ag:22, cl:"Brighton",          sv:88,  ca:14,  r:81 },
    { n:"Mark Flekken",         p:"GK",  ag:31, cl:"Brentford",         sv:108, ca:12,  r:80 },
    { n:"Remko Pasveer",        p:"GK",  ag:41, cl:"Ajax",              sv:118, ca:6,   r:78 },
    { n:"Virgil van Dijk",      p:"DEF", ag:34, cl:"Liverpool",         g:14,   as:6,   ca:62,  r:87 },
    { n:"Stefan de Vrij",       p:"DEF", ag:33, cl:"Inter Milan",       g:10,   as:4,   ca:52,  r:83 },
    { n:"Denzel Dumfries",      p:"DEF", ag:29, cl:"Inter Milan",       g:14,   as:18,  ca:52,  r:83 },
    { n:"Matthijs de Ligt",     p:"DEF", ag:26, cl:"Man United",        g:8,    as:4,   ca:46,  r:84 },
    { n:"Nathan Aké",           p:"DEF", ag:30, cl:"Man City",          g:6,    as:4,   ca:38,  r:82 },
    { n:"Jordi Aerts",          p:"DEF", ag:24, cl:"PSV Eindhoven",     g:2,    as:6,   ca:12,  r:79 },
    { n:"Frenkie de Jong",      p:"MID", ag:28, cl:"Barcelona",         g:10,   as:16,  ca:58,  r:86 },
    { n:"Davy Klaassen",        p:"MID", ag:31, cl:"Ajax",              g:12,   as:14,  ca:42,  r:80 },
    { n:"Teun Koopmeiners",     p:"MID", ag:27, cl:"Juventus",          g:14,   as:16,  ca:22,  r:84 },
    { n:"Tijjani Reijnders",    p:"MID", ag:26, cl:"AC Milan",          g:10,   as:14,  ca:18,  r:83 },
    { n:"Ryan Gravenberch",     p:"MID", ag:23, cl:"Liverpool",         g:6,    as:10,  ca:24,  r:82 },
    { n:"Memphis Depay",        p:"FWD", ag:31, cl:"Corinthians",       g:46,   as:30,  ca:90,  r:82 },
    { n:"Cody Gakpo",           p:"FWD", ag:26, cl:"Liverpool",         g:18,   as:12,  ca:38,  r:84 },
    { n:"Donyell Malen",        p:"FWD", ag:26, cl:"Dortmund",          g:12,   as:10,  ca:26,  r:81 },
    { n:"Wout Weghorst",        p:"FWD", ag:32, cl:"Hoffenheim",        g:12,   as:6,   ca:34,  r:79 },
    { n:"Noa Lang",             p:"FWD", ag:25, cl:"PSV Eindhoven",     g:8,    as:10,  ca:14,  r:81 },
    { n:"Xavi Simons",          p:"MID", ag:22, cl:"PSG",               g:8,    as:14,  ca:18,  r:84 },
    { n:"Brian Brobbey",        p:"FWD", ag:23, cl:"Ajax",              g:10,   as:6,   ca:12,  r:80 },
    { n:"Steven Bergwijn",      p:"FWD", ag:27, cl:"Ajax",              g:12,   as:14,  ca:28,  r:81 },
    { n:"Quinten Timber",       p:"MID", ag:22, cl:"Arsenal",           g:4,    as:8,   ca:10,  r:80 },
  ],
  norway: [
    { n:"Ørjan Nyland",         p:"GK",  ag:34, cl:"Internazionale",    sv:118, ca:28,  r:80 },
    { n:"Erling Haaland",       p:"FWD", ag:26, cl:"Man City",          g:48,   as:18,  ca:42,  r:93 },
    { n:"Martin Ødegaard",      p:"MID", ag:27, cl:"Arsenal",           g:22,   as:28,  ca:62,  r:87 },
    { n:"Alexander Sørloth",    p:"FWD", ag:29, cl:"Atletico Madrid",   g:22,   as:10,  ca:48,  r:82 },
    { n:"Sander Berge",         p:"MID", ag:27, cl:"Burnley",           g:8,    as:12,  ca:38,  r:80 },
    { n:"Stefan Strandberg",    p:"DEF", ag:33, cl:"Udinese",           g:4,    as:2,   ca:44,  r:77 },
    { n:"Leo Østigård",         p:"DEF", ag:25, cl:"Napoli",            g:4,    as:1,   ca:22,  r:78 },
    { n:"Fredrik Aursnes",      p:"MID", ag:29, cl:"Benfica",           g:4,    as:8,   ca:28,  r:79 },
    { n:"Morten Thorsby",       p:"MID", ag:29, cl:"Union Berlin",      g:4,    as:6,   ca:38,  r:78 },
    { n:"Mohamed Elyounoussi",  p:"FWD", ag:30, cl:"Southampton",       g:14,   as:12,  ca:62,  r:78 },
    { n:"Kristian Thorstvedt",  p:"MID", ag:24, cl:"Sassuolo",          g:6,    as:8,   ca:18,  r:77 },
    { n:"Julian Ryerson",       p:"DEF", ag:27, cl:"Dortmund",          g:2,    as:8,   ca:32,  r:78 },
    { n:"Mathias Normann",      p:"MID", ag:28, cl:"Anderlecht",        g:4,    as:6,   ca:32,  r:77 },
    { n:"Antonio Nusa",         p:"FWD", ag:20, cl:"RB Leipzig",        g:6,    as:8,   ca:14,  r:78 },
    { n:"Håvard Nielsen",       p:"FWD", ag:30, cl:"Genoa",             g:10,   as:6,   ca:22,  r:76 },
    { n:"Stian Gregersen",      p:"DEF", ag:29, cl:"Bordeaux",          g:2,    as:1,   ca:22,  r:76 },
    { n:"Tobias Svendsen",      p:"MID", ag:22, cl:"Lillestrøm",        g:2,    as:4,   ca:8,   r:73 },
    { n:"Patrick Berg",         p:"MID", ag:26, cl:"Lens",              g:2,    as:4,   ca:18,  r:75 },
  ],
  south_korea: [
    { n:"Kim Seung-gyu",        p:"GK",  ag:35, cl:"Vissel Kobe",       sv:128, ca:78,  r:79 },
    { n:"Jo Hyeon-woo",         p:"GK",  ag:33, cl:"Ulsan HD",          sv:108, ca:38,  r:76 },
    { n:"Heung-min Son",        p:"FWD", ag:33, cl:"Tottenham",         g:52,   as:28,  ca:114, r:84 },
    { n:"Kim Min-jae",          p:"DEF", ag:28, cl:"Bayern Munich",     g:8,    as:2,   ca:62,  r:84 },
    { n:"Lee Kang-in",          p:"MID", ag:24, cl:"PSG",               g:12,   as:14,  ca:44,  r:82 },
    { n:"Hwang Hee-chan",        p:"FWD", ag:28, cl:"Wolves",            g:18,   as:10,  ca:52,  r:81 },
    { n:"Kim Jin-su",           p:"DEF", ag:33, cl:"Jiangsu FC",        g:4,    as:8,   ca:78,  r:78 },
    { n:"Jung Woo-young",       p:"MID", ag:33, cl:"Al Qadsiah",        g:4,    as:6,   ca:78,  r:78 },
    { n:"Hwang In-beom",        p:"MID", ag:28, cl:"Vancouver Whitecaps",g:6,   as:10,  ca:52,  r:79 },
    { n:"Cho Gue-sung",         p:"FWD", ag:26, cl:"Jeonbuk",           g:14,   as:4,   ca:28,  r:78 },
    { n:"Kim Young-gwon",       p:"DEF", ag:35, cl:"Ulsan HD",          g:6,    as:2,   ca:104, r:77 },
    { n:"Oh Hyeon-gyu",         p:"FWD", ag:23, cl:"Celtic",            g:8,    as:4,   ca:22,  r:79 },
    { n:"Jeong Woo-yeong",      p:"MID", ag:25, cl:"Freiburg",          g:6,    as:8,   ca:28,  r:78 },
    { n:"Kim Tae-hwan",         p:"DEF", ag:31, cl:"Ulsan HD",          g:2,    as:4,   ca:62,  r:77 },
    { n:"Bae Jun-ho",           p:"MID", ag:22, cl:"Stoke City",        g:4,    as:6,   ca:16,  r:77 },
    { n:"Lee Jae-sung",         p:"MID", ag:32, cl:"Mainz",             g:8,    as:10,  ca:68,  r:78 },
    { n:"Go Myong-jin",         p:"DEF", ag:26, cl:"Gangwon FC",        g:2,    as:2,   ca:18,  r:75 },
    { n:"Na Sang-ho",           p:"FWD", ag:26, cl:"Valladolid",        g:4,    as:6,   ca:18,  r:76 },
  ],
  mexico: [
    { n:"Guillermo Ochoa",      p:"GK",  ag:39, cl:"Salernitana",       sv:148, ca:148, r:80 },
    { n:"Raúl Jiménez",         p:"FWD", ag:33, cl:"Fulham",            g:38,   as:12,  ca:84,  r:79 },
    { n:"Hirving Lozano",       p:"FWD", ag:30, cl:"PSV Eindhoven",     g:30,   as:18,  ca:72,  r:82 },
    { n:"Edson Álvarez",        p:"MID", ag:27, cl:"West Ham",          g:8,    as:8,   ca:72,  r:80 },
    { n:"Henry Martín",         p:"FWD", ag:32, cl:"Club América",      g:22,   as:8,   ca:38,  r:78 },
    { n:"Héctor Herrera",       p:"MID", ag:35, cl:"Houston Dynamo",    g:12,   as:16,  ca:110, r:77 },
    { n:"Andrés Guardado",      p:"MID", ag:38, cl:"Real Betis",        g:28,   as:32,  ca:181, r:75 },
    { n:"Jesús Gallardo",       p:"DEF", ag:29, cl:"Monterrey",         g:2,    as:8,   ca:58,  r:77 },
    { n:"César Montes",         p:"DEF", ag:27, cl:"Monterrey",         g:4,    as:2,   ca:38,  r:76 },
    { n:"Alexis Vega",          p:"FWD", ag:27, cl:"Chivas",            g:14,   as:10,  ca:32,  r:78 },
    { n:"Orbelin Pineda",       p:"MID", ag:28, cl:"AEK Athens",        g:12,   as:14,  ca:44,  r:77 },
    { n:"Roberto Alvarado",     p:"MID", ag:24, cl:"Chivas",            g:8,    as:10,  ca:28,  r:76 },
    { n:"Kevin Álvarez",        p:"DEF", ag:25, cl:"Pachuca",           g:2,    as:6,   ca:18,  r:76 },
    { n:"Johan Vásquez",        p:"DEF", ag:25, cl:"Genoa",             g:2,    as:2,   ca:28,  r:76 },
    { n:"Erick Gutiérrez",      p:"MID", ag:28, cl:"PSV Eindhoven",     g:6,    as:8,   ca:32,  r:76 },
    { n:"Jesús Corona",         p:"DEF", ag:32, cl:"Sevilla",           g:4,    as:10,  ca:78,  r:77 },
    { n:"Uriel Antuna",         p:"FWD", ag:26, cl:"Cruz Azul",         g:8,    as:8,   ca:28,  r:76 },
    { n:"Santiago Giménez",     p:"FWD", ag:23, cl:"Feyenoord",         g:14,   as:6,   ca:22,  r:80 },
  ],
  belgium: [
    { n:"Thibaut Courtois",     p:"GK",  ag:33, cl:"Real Madrid",       sv:168, ca:104, r:91 },
    { n:"Simon Mignolet",       p:"GK",  ag:37, cl:"Club Brugge",       sv:128, ca:36,  r:82 },
    { n:"Kevin De Bruyne",      p:"MID", ag:34, cl:"Man City",          g:28,   as:56,  ca:102, r:91 },
    { n:"Romelu Lukaku",        p:"FWD", ag:31, cl:"Napoli",            g:84,   as:22,  ca:108, r:85 },
    { n:"Jan Vertonghen",       p:"DEF", ag:38, cl:"Anderlecht",        g:10,   as:8,   ca:152, r:78 },
    { n:"Toby Alderweireld",    p:"DEF", ag:36, cl:"Beerschot VA",      g:6,    as:4,   ca:128, r:78 },
    { n:"Axel Witsel",          p:"MID", ag:36, cl:"Atletico Madrid",   g:12,   as:8,   ca:130, r:80 },
    { n:"Jeremy Doku",          p:"FWD", ag:22, cl:"Man City",          g:8,    as:12,  ca:22,  r:83 },
    { n:"Yannick Carrasco",     p:"MID", ag:31, cl:"Al-Shabab",         g:16,   as:18,  ca:62,  r:81 },
    { n:"Amadou Onana",         p:"MID", ag:23, cl:"Aston Villa",       g:6,    as:8,   ca:28,  r:82 },
    { n:"Loïs Openda",          p:"FWD", ag:24, cl:"RB Leipzig",        g:14,   as:8,   ca:22,  r:82 },
    { n:"Leandro Trossard",     p:"FWD", ag:29, cl:"Arsenal",           g:14,   as:12,  ca:38,  r:83 },
    { n:"Thomas Meunier",       p:"DEF", ag:33, cl:"Trabzonspor",       g:8,    as:10,  ca:68,  r:79 },
    { n:"Wout Faes",            p:"DEF", ag:26, cl:"Leicester City",    g:2,    as:2,   ca:18,  r:79 },
    { n:"Charles De Ketelaere", p:"MID", ag:24, cl:"Atalanta",          g:12,   as:14,  ca:28,  r:82 },
    { n:"Arthur Theate",        p:"DEF", ag:25, cl:"Rennes",            g:4,    as:4,   ca:18,  r:79 },
    { n:"Johan Bakayoko",       p:"FWD", ag:22, cl:"PSV Eindhoven",     g:6,    as:10,  ca:12,  r:78 },
    { n:"Orel Mangala",         p:"MID", ag:26, cl:"Nottm Forest",      g:2,    as:6,   ca:22,  r:79 },
  ],
  morocco: [
    { n:"Yassine Bounou",       p:"GK",  ag:34, cl:"Al-Hilal",          sv:138, ca:48,  r:84 },
    { n:"Munir Mohamedi",       p:"GK",  ag:36, cl:"Hatayspor",         sv:108, ca:28,  r:77 },
    { n:"Achraf Hakimi",        p:"DEF", ag:26, cl:"PSG",               g:14,   as:18,  ca:62,  r:86 },
    { n:"Romain Saïss",         p:"DEF", ag:35, cl:"Beşiktaş",          g:6,    as:4,   ca:72,  r:79 },
    { n:"Jawad El Yamiq",       p:"DEF", ag:33, cl:"Real Valladolid",   g:4,    as:2,   ca:38,  r:78 },
    { n:"Noussair Mazraoui",    p:"DEF", ag:27, cl:"Man United",        g:6,    as:10,  ca:42,  r:81 },
    { n:"Hakim Ziyech",         p:"MID", ag:32, cl:"Galatasaray",       g:22,   as:28,  ca:68,  r:82 },
    { n:"Azzedine Ounahi",      p:"MID", ag:24, cl:"Marseille",         g:4,    as:10,  ca:28,  r:81 },
    { n:"Sofyan Amrabat",       p:"MID", ag:28, cl:"Fenerbahçe",        g:4,    as:6,   ca:58,  r:82 },
    { n:"Selim Amallah",        p:"MID", ag:28, cl:"Standard Liège",    g:8,    as:10,  ca:28,  r:78 },
    { n:"Youssef En-Nesyri",    p:"FWD", ag:28, cl:"Fenerbahçe",        g:26,   as:8,   ca:52,  r:80 },
    { n:"Abdessamad Ezzalzouli",p:"FWD", ag:23, cl:"Betis",             g:6,    as:8,   ca:22,  r:79 },
    { n:"Ilias Chair",          p:"MID", ag:27, cl:"QPR",               g:12,   as:14,  ca:18,  r:78 },
    { n:"Sofiane Boufal",       p:"FWD", ag:30, cl:"Angers",            g:14,   as:12,  ca:52,  r:79 },
    { n:"Aymen Barkok",         p:"MID", ag:27, cl:"Fortuna Düsseldorf",g:4,    as:6,   ca:18,  r:76 },
    { n:"Zakaria Aboukhlal",    p:"FWD", ag:24, cl:"Toulouse",          g:6,    as:6,   ca:18,  r:77 },
    { n:"Adam Masina",          p:"DEF", ag:30, cl:"Watford",           g:2,    as:4,   ca:38,  r:77 },
    { n:"Yahia Attiat-Allah",   p:"DEF", ag:28, cl:"Zamalek",           g:2,    as:4,   ca:28,  r:76 },
  ],
  japan: [
    { n:"Shuichi Gonda",        p:"GK",  ag:35, cl:"Shimizu S-Pulse",   sv:128, ca:62,  r:78 },
    { n:"Zion Suzuki",          p:"GK",  ag:22, cl:"Sint-Truiden",      sv:68,  ca:12,  r:76 },
    { n:"Takehiro Tomiyasu",    p:"DEF", ag:26, cl:"Arsenal",           g:4,    as:6,   ca:48,  r:82 },
    { n:"Maya Yoshida",         p:"DEF", ag:36, cl:"Vissel Kobe",       g:8,    as:4,   ca:128, r:76 },
    { n:"Daichi Kamada",        p:"MID", ag:28, cl:"Crystal Palace",    g:16,   as:18,  ca:52,  r:83 },
    { n:"Kaoru Mitoma",         p:"FWD", ag:27, cl:"Brighton",          g:18,   as:14,  ca:42,  r:83 },
    { n:"Wataru Endo",          p:"MID", ag:31, cl:"Liverpool",         g:4,    as:6,   ca:48,  r:80 },
    { n:"Ritsu Doan",           p:"FWD", ag:26, cl:"Freiburg",          g:16,   as:12,  ca:52,  r:81 },
    { n:"Hiroki Ito",           p:"DEF", ag:25, cl:"Stuttgart",         g:4,    as:4,   ca:32,  r:80 },
    { n:"Ao Tanaka",            p:"MID", ag:26, cl:"Dortmund",          g:8,    as:10,  ca:42,  r:79 },
    { n:"Keito Nakamura",       p:"FWD", ag:22, cl:"Stade Reims",       g:8,    as:8,   ca:18,  r:78 },
    { n:"Kou Itakura",          p:"DEF", ag:27, cl:"Borussia M'gladbach",g:4,   as:2,   ca:28,  r:79 },
    { n:"Takuma Asano",         p:"FWD", ag:29, cl:"VfL Bochum",        g:12,   as:8,   ca:38,  r:77 },
    { n:"Junya Ito",            p:"FWD", ag:31, cl:"Stade Reims",       g:12,   as:10,  ca:52,  r:78 },
    { n:"Takefusa Kubo",        p:"FWD", ag:23, cl:"Real Sociedad",     g:12,   as:10,  ca:32,  r:82 },
    { n:"Yuya Osako",           p:"FWD", ag:34, cl:"Vissel Kobe",       g:16,   as:6,   ca:72,  r:76 },
    { n:"Hidemasa Morita",      p:"MID", ag:29, cl:"Sporting CP",       g:4,    as:8,   ca:28,  r:79 },
    { n:"Yuki Soma",            p:"MID", ag:27, cl:"Nagoya Grampus",    g:4,    as:6,   ca:22,  r:75 },
  ],
  usa: [
    { n:"Matt Turner",          p:"GK",  ag:30, cl:"Nottm Forest",      sv:118, ca:36,  r:79 },
    { n:"Ethan Horvath",        p:"GK",  ag:29, cl:"Luton Town",        sv:88,  ca:14,  r:75 },
    { n:"Christian Pulisic",    p:"FWD", ag:27, cl:"AC Milan",          g:32,   as:22,  ca:68,  r:83 },
    { n:"Weston McKennie",      p:"MID", ag:26, cl:"Juventus",          g:14,   as:12,  ca:52,  r:80 },
    { n:"Tyler Adams",          p:"MID", ag:26, cl:"Bournemouth",       g:4,    as:12,  ca:48,  r:80 },
    { n:"Gio Reyna",            p:"MID", ag:22, cl:"Dortmund",          g:8,    as:12,  ca:28,  r:81 },
    { n:"Timothy Weah",         p:"FWD", ag:25, cl:"Juventus",          g:8,    as:8,   ca:38,  r:79 },
    { n:"Yunus Musah",          p:"MID", ag:22, cl:"AC Milan",          g:4,    as:8,   ca:42,  r:79 },
    { n:"Antonee Robinson",     p:"DEF", ag:27, cl:"Fulham",            g:4,    as:10,  ca:52,  r:79 },
    { n:"Sergiño Dest",         p:"DEF", ag:24, cl:"AC Milan",          g:4,    as:12,  ca:38,  r:79 },
    { n:"Walker Zimmerman",     p:"DEF", ag:32, cl:"Nashville SC",      g:4,    as:2,   ca:42,  r:75 },
    { n:"Mark McKenzie",        p:"DEF", ag:25, cl:"Genk",              g:2,    as:2,   ca:22,  r:75 },
    { n:"Ricardo Pepi",         p:"FWD", ag:22, cl:"PSV Eindhoven",     g:12,   as:6,   ca:28,  r:78 },
    { n:"Josh Sargent",         p:"FWD", ag:24, cl:"Norwich City",      g:10,   as:6,   ca:28,  r:76 },
    { n:"Cameron Carter-Vickers",p:"DEF",ag:27, cl:"Celtic",            g:2,    as:2,   ca:18,  r:77 },
    { n:"DeAndre Yedlin",       p:"DEF", ag:32, cl:"Inter Miami",       g:2,    as:4,   ca:92,  r:74 },
    { n:"Luca de la Torre",     p:"MID", ag:27, cl:"Celta Vigo",        g:4,    as:6,   ca:22,  r:76 },
    { n:"Jesús Ferreira",       p:"FWD", ag:24, cl:"FC Dallas",         g:14,   as:8,   ca:28,  r:76 },
  ],
  uruguay: [
    { n:"Sergio Rochet",        p:"GK",  ag:30, cl:"Nacional",          sv:98,  ca:22,  r:78 },
    { n:"Fernando Muslera",     p:"GK",  ag:38, cl:"Galatasaray",       sv:148, ca:132, r:77 },
    { n:"Darwin Núñez",         p:"FWD", ag:26, cl:"Liverpool",         g:18,   as:8,   ca:38,  r:84 },
    { n:"Federico Valverde",    p:"MID", ag:26, cl:"Real Madrid",       g:14,   as:12,  ca:52,  r:87 },
    { n:"José María Giménez",   p:"DEF", ag:30, cl:"Atletico Madrid",   g:6,    as:2,   ca:68,  r:83 },
    { n:"Diego Godín",          p:"DEF", ag:39, cl:"Vélez Sarsfield",   g:10,   as:2,   ca:160, r:74 },
    { n:"Rodrigo Bentancur",    p:"MID", ag:27, cl:"Tottenham",         g:8,    as:10,  ca:58,  r:82 },
    { n:"Matías Vecino",        p:"MID", ag:33, cl:"Lazio",             g:10,   as:8,   ca:68,  r:79 },
    { n:"Ronald Araújo",        p:"DEF", ag:25, cl:"Barcelona",         g:6,    as:2,   ca:32,  r:84 },
    { n:"Facundo Torres",       p:"FWD", ag:24, cl:"Orlando City",      g:10,   as:8,   ca:18,  r:78 },
    { n:"Facundo Pellistri",    p:"FWD", ag:23, cl:"Man United",        g:6,    as:8,   ca:22,  r:78 },
    { n:"Maxi Gómez",           p:"FWD", ag:28, cl:"Valencia",          g:10,   as:4,   ca:32,  r:77 },
    { n:"Nahitan Nández",       p:"MID", ag:28, cl:"Cagliari",          g:4,    as:8,   ca:48,  r:79 },
    { n:"Mathías Olivera",      p:"DEF", ag:27, cl:"Napoli",            g:2,    as:6,   ca:32,  r:79 },
    { n:"Sebastián Coates",     p:"DEF", ag:34, cl:"Sporting CP",       g:4,    as:2,   ca:48,  r:78 },
    { n:"Giorgian de Arrascaeta",p:"MID",ag:31, cl:"Flamengo",          g:16,   as:14,  ca:62,  r:82 },
    { n:"Marcelo Saracchi",     p:"DEF", ag:27, cl:"RB Leipzig",        g:2,    as:4,   ca:18,  r:76 },
    { n:"Edinson Cavani",       p:"FWD", ag:37, cl:"Boca Juniors",      g:58,   as:14,  ca:136, r:76 },
  ],
};

// Pad out teams without squads with lightweight data
const TEAM_DEFAULTS = {};
for (const tid of Object.keys(TEAMS)) {
  if (!PLAYERS[tid]) PLAYERS[tid] = generateDefaultSquad(tid);
}

function generateDefaultSquad(tid) {
  const t = TEAMS[tid];
  const rank = t.fifa_rank;
  const baseRating = Math.max(68, Math.min(84, 90 - Math.floor(rank / 5)));
  const templates = [
    { n:"Goalkeeper #1",   p:"GK",  ag:28, cl:"Domestic Club",   sv:110, ca:30, r:baseRating-2 },
    { n:"Goalkeeper #2",   p:"GK",  ag:25, cl:"Domestic Club",   sv:80,  ca:12, r:baseRating-5 },
    { n:"Defender #1",     p:"DEF", ag:29, cl:"European Club",   g:4,    as:2,  ca:40, r:baseRating+1 },
    { n:"Defender #2",     p:"DEF", ag:27, cl:"Domestic Club",   g:2,    as:3,  ca:28, r:baseRating-1 },
    { n:"Defender #3",     p:"DEF", ag:30, cl:"Domestic Club",   g:1,    as:2,  ca:44, r:baseRating-2 },
    { n:"Defender #4",     p:"DEF", ag:25, cl:"Domestic Club",   g:1,    as:4,  ca:18, r:baseRating-2 },
    { n:"Midfielder #1",   p:"MID", ag:28, cl:"European Club",   g:8,    as:10, ca:52, r:baseRating+2 },
    { n:"Midfielder #2",   p:"MID", ag:26, cl:"Domestic Club",   g:5,    as:8,  ca:38, r:baseRating },
    { n:"Midfielder #3",   p:"MID", ag:31, cl:"Domestic Club",   g:6,    as:6,  ca:60, r:baseRating-1 },
    { n:"Forward #1",      p:"FWD", ag:27, cl:"European Club",   g:18,   as:8,  ca:42, r:baseRating+3 },
    { n:"Forward #2",      p:"FWD", ag:25, cl:"Domestic Club",   g:12,   as:6,  ca:28, r:baseRating+1 },
    { n:"Forward #3",      p:"FWD", ag:29, cl:"Domestic Club",   g:10,   as:4,  ca:36, r:baseRating },
  ];
  return templates;
}

// ============================================================
//  UTILITY: Squad Score from avg EA rating
// ============================================================
function getSquadScore(players) {
  if (!players || players.length === 0) return 50;
  const avg = players.reduce((sum, p) => sum + p.r, 0) / players.length;
  return Math.min(100, Math.max(0, Math.round((avg - 65) / 25 * 100)));
}

// Expose for use in other files
if (typeof module !== 'undefined') {
  module.exports = { TEAMS, MATCHES, PLAYERS, getSquadScore };
}
